# Generated by Django 4.2.18 on 2025-01-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_assigned',
        ),
        migrations.AddField(
            model_name='task',
            name='date_created',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
    ]
